//
//  AchievementsInteractor.swift
//  SmartInvesting
//
//  Created Marcos Garcia on 1/5/19.
//  Copyright © 2019 Marcos Garcia. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AchievementsInteractor: AchievementsInteractorInputProtocol {

    weak var presenter: AchievementsInteractorOutputProtocol?
}
