//
//  AchievementsProtocols.swift
//  SmartInvesting
//
//  Created Marcos Garcia on 1/5/19.
//  Copyright © 2019 Marcos Garcia. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol AchievementsWireframeProtocol: class {

}
//MARK: Presenter -
protocol AchievementsPresenterProtocol: class {

    var interactor: AchievementsInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol AchievementsInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol AchievementsInteractorInputProtocol: class {

    var presenter: AchievementsInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol AchievementsViewProtocol: class {

    var presenter: AchievementsPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
