//
//  AchievementsProtocols.swift
//  SmartInvesting
//
//  Created Marcos Garcia on 1/5/19.
//  Copyright © 2019 Marcos Garcia. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol AchievementsWireframeProtocol: class {

}
//MARK: Presenter -
protocol AchievementsPresenterProtocol: class {

    var interactor: AchievementsInteractorInputProtocol? { get set }
    
    func retrieveAchievements() -> [Achievement]?
}

//MARK: Interactor -
protocol AchievementsInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol AchievementsInteractorInputProtocol: class {

    var presenter: AchievementsInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getAchievements() -> [Achievement]?
}

//MARK: View -
protocol AchievementsViewProtocol: class {

    var presenter: AchievementsPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}

protocol AchievementProtocol {
    var id: Int { get set }
    var level: String { get set }
    var progress: Int { get set }
    var total: Int { get set }
    var bg_image_url: URL? { get set }
    var accessible: Bool { get set }
}
