//
//  AchievementsInteractor.swift
//  SmartInvesting
//
//  Created Marcos Garcia on 1/5/19.
//  Copyright © 2019 Marcos Garcia. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AchievementsInteractor: AchievementsInteractorInputProtocol {
    
    weak var presenter: AchievementsInteractorOutputProtocol?
    
    func getAchievements() -> [Achievement]? {
        
        /// Get the information from local json
        guard let dictionaryFromFile = JSONFormatter.parseWith(file: "achievements") else {
            return nil
        }
        
        /// Get the dictionary with the achievements
        guard let achievementsDictionary = dictionaryFromFile["achievements"] as? [[String : Any]] else {
            return nil
        }
        
        /// Get an instance of the Factory
        let factory = AchievementsFactory.shared()
        
        /// Use the factory to create Achievements
        let achievements = factory.makeAchievements(achievements: achievementsDictionary)
        
        return achievements
    }
}
